name: Windows 11 RDP Setup

on:
  workflow_dispatch:

jobs:
  setup-windows11-rdp:
    runs-on: windows-11  # Windows 11 runner ကိုသုံးပါ
    timeout-minutes: 360  # 6 hours maximum

    steps:
    - name: Configure RDP Settings
      run: |
        # Enable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
        
        # Disable NLA for easier connection (can be enabled later for security)
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
        
        # Configure firewall to allow RDP
        netsh advfirewall firewall set rule group="Remote Desktop" new enable=Yes
        
        # Restart Terminal Services
        Restart-Service -Name TermService -Force

    - name: Create RDP User Account
      run: |
        # Strong password generation
        Add-Type -AssemblyName System.Web
        $password = [System.Web.Security.Membership]::GeneratePassword(16, 4)
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        
        # Create user
        New-LocalUser -Name "RDPUser" -Password $securePassword -AccountNeverExpires -PasswordNeverExpires
        Add-LocalGroupMember -Group "Administrators" -Member "RDPUser"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDPUser"
        
        # Store credentials in environment variables (masked in logs)
        Write-Output "RDP_USER=RDPUser" >> $env:GITHUB_ENV
        Write-Output "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

    - name: Install Tailscale
      run: |
        # Download and install Tailscale
        $tsInstaller = "$env:TEMP\tailscale.msi"
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-amd64.msi" -OutFile $tsInstaller
        Start-Process msiexec.exe -ArgumentList "/i", "`"$tsInstaller`"", "/quiet", "/norestart" -Wait
        Remove-Item $tsInstaller -Force

    - name: Connect to Tailscale
      run: |
        # Authenticate with Tailscale
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=win11-gh-runner-$env:GITHUB_RUN_ID --accept-routes
        
        # Get Tailscale IP
        $tsIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Output "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
        
        # Wait for IP assignment
        $retries = 0
        while (-not $tsIP -and $retries -lt 10) {
            Start-Sleep -Seconds 5
            $tsIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
            $retries++
        }

    - name: Display Connection Information
      run: |
        Write-Host "=============================================="
        Write-Host "Windows 11 RDP Connection Ready!"
        Write-Host "IP Address: $env:TAILSCALE_IP"
        Write-Host "Username: $env:RDP_USER"
        Write-Host "Password: $env:RDP_PASSWORD"
        Write-Host "=============================================="
        
        # Keep the runner active
        Write-Host "RDP session will remain active for 6 hours maximum"
        Write-Host "Press Ctrl+C in the workflow console to terminate early"

    - name: Keep Runner Active
      run: |
        # Keep the runner active until manually stopped
        $startTime = Get-Date
        $maxDuration = New-TimeSpan -Hours 6
        
        while (((Get-Date) - $startTime) -lt $maxDuration) {
            Write-Host "[$(Get-Date)] RDP session active - IP: $env:TAILSCALE_IP"
            Start-Sleep -Seconds 60
        }
        
        Write-Host "Maximum duration reached, stopping runner"
